/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler */

#ifndef _Included_cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler
#define _Included_cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler
 * Method:    ntInitForSocketDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler_ntInitForSocketDir
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler
 * Method:    ntPeekConnection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler_ntPeekConnection
  (JNIEnv *, jclass);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler
 * Method:    ntRequestConnection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler_ntRequestConnection
  (JNIEnv *, jclass);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler
 * Method:    ntWaitForConnection
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler_ntWaitForConnection
  (JNIEnv *, jclass, jint);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler
 * Method:    getIpcPidFileFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler_getIpcPidFileFD
  (JNIEnv *, jclass);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler
 * Method:    getKernelArchitecture
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler_getKernelArchitecture
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler_IpcConnectionListener */

#ifndef _Included_cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler_IpcConnectionListener
#define _Included_cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler_IpcConnectionListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler_RemoteEventHandler */

#ifndef _Included_cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler_RemoteEventHandler
#define _Included_cc_ioctl_opdisplaytuner_ipc_daemon_IpcNativeHandler_RemoteEventHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy */

#ifndef _Included_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
#define _Included_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    isConnected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_isConnected
  (JNIEnv *, jobject);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    getVersionName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_getVersionName
  (JNIEnv *, jobject);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    getVersionCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_getVersionCode
  (JNIEnv *, jobject);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    getBuildUuid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_getBuildUuid
  (JNIEnv *, jobject);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    getSelfPid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_getSelfPid
  (JNIEnv *, jobject);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    exitProcess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_exitProcess
  (JNIEnv *, jobject);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    isDeviceSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_isDeviceSupported
  (JNIEnv *, jobject);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    initHwServiceConnection
 * Signature: ([Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_initHwServiceConnection
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    isDisplayFeatureHidlServivceAttached
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_isDisplayFeatureHidlServivceAttached
  (JNIEnv *, jobject);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    isDimLayerHbmEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_isDimLayerHbmEnabled
  (JNIEnv *, jobject);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    setDimLayerHbmEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_setDimLayerHbmEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    isDimLayerHbmForceEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_isDimLayerHbmForceEnabled
  (JNIEnv *, jobject);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    setDimLayerHbmForceEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_setDimLayerHbmForceEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    ntGetHistoryIoEvents
 * Signature: (II)Lcc/ioctl/opdisplaytuner/ipc/daemon/internal/DispTunerDaemonProxy/RawHistoryIoEventList;
 */
JNIEXPORT jobject JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_ntGetHistoryIoEvents
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    deviceDriverIoctl0
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_deviceDriverIoctl0
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    getDaemonStatus
 * Signature: ()Lcc/ioctl/opdisplaytuner/ipc/daemon/IDispTunerDaemon/DaemonStatus;
 */
JNIEXPORT jobject JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_getDaemonStatus
  (JNIEnv *, jobject);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    clearHistoryIoEvents
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_clearHistoryIoEvents
  (JNIEnv *, jobject);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    getLogsPartial
 * Signature: (II)[Lcc/ioctl/opdisplaytuner/ipc/daemon/IDispTunerDaemon/LogEntryRecord;
 */
JNIEXPORT jobjectArray JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_getLogsPartial
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy
 * Method:    waitForEvent
 * Signature: ()Lcc/ioctl/opdisplaytuner/ipc/daemon/internal/DispTunerDaemonProxy/NativeEventPacket;
 */
JNIEXPORT jobject JNICALL Java_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_waitForEvent
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_RawHistoryIoEventList */

#ifndef _Included_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_RawHistoryIoEventList
#define _Included_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_RawHistoryIoEventList
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_RawIoEventPacket */

#ifndef _Included_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_RawIoEventPacket
#define _Included_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_RawIoEventPacket
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_NativeEventPacket */

#ifndef _Included_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_NativeEventPacket
#define _Included_cc_ioctl_opdisplaytuner_ipc_daemon_internal_DispTunerDaemonProxy_NativeEventPacket
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
